name: Performance Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  analyze:
    runs-on: ubuntu-latest
    name: Analyze URLs
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli
      
      - name: Create Lighthouse configuration
        run: |
          cat > lighthouserc.json << 'EOL'
          {
            "ci": {
              "collect": {
                "settings": {
                  "extraHeaders": {
                    "Cookie": "access_token=${{ secrets.ACCESS_TOKEN }}"
                  }
                },
                "url": [
                  "https://fernando-espinosa-clip.github.io/Score-Calculator/",
                  "https://fernando-espinosa-clip.github.io/Score-Calculator/?page=results"
                ]
              },
              "assert": {
                "assertions": {
                  "categories:performance": ["error", {"minScore": 0.8}],
                  "categories:accessibility": ["error", {"minScore": 0.9}],
                  "categories:best-practices": ["error", {"minScore": 0.9}],
                  "categories:seo": ["error", {"minScore": 0.9}]
                }
              },
              "upload": {
                "target": "temporary-public-storage"
              }
            }
          }
          EOL
      
      - name: Run Lighthouse CI
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      
      - name: Generate Performance Report
        run: |
          echo "# Performance Analysis Results" > performance-report.md
          echo "" >> performance-report.md
          echo "## URLs Analyzed" >> performance-report.md
          echo "- https://fernando-espinosa-clip.github.io/Score-Calculator/" >> performance-report.md
          echo "- https://fernando-espinosa-clip.github.io/Score-Calculator/?page=results" >> performance-report.md
          echo "" >> performance-report.md
          echo "## Scores" >> performance-report.md
          echo "The detailed scores can be found in the Lighthouse CI report." >> performance-report.md
          echo "" >> performance-report.md
          echo "## Summary" >> performance-report.md
          echo "This analysis was performed with an access_token cookie injected before each evaluation." >> performance-report.md
      
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const report = fs.readFileSync('performance-report.md', 'utf8');
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });